"use client";

import { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Activity, Users, Target, IndianRupee, Trophy, ShieldAlert } from "lucide-react";
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { toast } from "sonner";

export default function AdminAnalyticsPage() {
  const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [range,setRange]=useState("30d"); const [type,setType]=useState("all"); const [category,setCategory]=useState("all");
  const load=async()=>{setLoading(true);try{const res=await fetch(`/api/admin/analytics?range=${range}&type=${type}&category=${encodeURIComponent(category)}`);const json=await res.json();if(!res.ok)throw new Error(json.error);setData(json)}catch(e:any){toast.error(e.message||"Failed to load analytics")}finally{setLoading(false)}};
  useEffect(()=>{load()},[range,type,category]);
  const o=data?.overview||{}; const cards=[{label:"Users",value:o.totalUsers||0,icon:Users},{label:"Active in Range",value:o.activeUsers||0,icon:Activity},{label:"Attempts",value:o.attempts||0,icon:Target},{label:"Accuracy",value:`${o.accuracy||0}%`,icon:Trophy},{label:"Revenue",value:`₹${Number(o.revenue||0).toLocaleString()}`,icon:IndianRupee},{label:"Cheat Terminations",value:o.cheatingTerminations||0,icon:ShieldAlert}];
  return <div className="p-4 md:p-6 space-y-6 max-w-7xl mx-auto"><div className="flex flex-col md:flex-row md:items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-primary">Intelligence Console</p><h1 className="text-2xl md:text-3xl font-black tracking-tight">Analytics</h1><p className="text-sm text-muted-foreground mt-1">Platform engagement, quiz performance and revenue trends.</p></div><div className="flex flex-wrap gap-2"><select value={range} onChange={e=>setRange(e.target.value)} className="h-10 rounded-xl border px-3 text-sm font-bold bg-background"><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="year">This year</option></select><select value={type} onChange={e=>setType(e.target.value)} className="h-10 rounded-xl border px-3 text-sm font-bold bg-background"><option value="all">All quiz types</option><option value="daily">Daily</option><option value="practice">Practice</option></select><select value={category} onChange={e=>setCategory(e.target.value)} className="h-10 rounded-xl border px-3 text-sm font-bold bg-background"><option value="all">All categories</option>{(data?.categories||[]).map((c:string)=><option key={c} value={c}>{c}</option>)}</select></div></div>
    {loading?<div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{[1,2,3,4,5,6].map(i=><Skeleton key={i} className="h-24 rounded-2xl"/>)}</div>:<><div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{cards.map(c=><Card key={c.label} className="rounded-2xl border-primary/5 shadow-sm"><CardContent className="p-4 flex justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground">{c.label}</p><p className="text-xl font-black mt-1">{c.value}</p></div><c.icon className="w-5 h-5 text-primary"/></CardContent></Card>)}</div>
    <div className="grid lg:grid-cols-2 gap-4"><Card className="rounded-2xl border-primary/5"><CardContent className="p-4 md:p-6"><h2 className="font-black mb-4">Quiz Activity</h2><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.dailyTrend||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Area type="monotone" dataKey="attempts" strokeWidth={2} fillOpacity={0.15}/><Area type="monotone" dataKey="correct" strokeWidth={2} fillOpacity={0.08}/></AreaChart></ResponsiveContainer></div></CardContent></Card><Card className="rounded-2xl border-primary/5"><CardContent className="p-4 md:p-6"><h2 className="font-black mb-4">Revenue Trend</h2><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.revenueTrend||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Bar dataKey="revenue"/></BarChart></ResponsiveContainer></div></CardContent></Card></div>
    <div className="grid lg:grid-cols-3 gap-4"><Card className="rounded-2xl border-primary/5 lg:col-span-2"><CardContent className="p-4 md:p-6"><h2 className="font-black mb-4">Most Attempted Questions</h2><div className="space-y-2">{(data.topQuestions||[]).map((q:any,i:number)=><div key={q.questionId} className="flex items-center justify-between rounded-xl bg-muted/30 px-3 py-3"><div className="flex items-center gap-3"><span className="w-7 h-7 rounded-lg bg-primary/10 text-primary flex items-center justify-center text-xs font-black">{i+1}</span><span className="font-mono text-xs truncate max-w-[220px]">{q.questionId}</span></div><div className="text-right"><div className="font-black text-sm">{q.attempts} attempts</div><div className="text-[10px] text-muted-foreground">{q.accuracy}% accuracy</div></div></div>)}{!(data.topQuestions||[]).length&&<p className="text-sm text-muted-foreground">No attempt data in this period.</p>}</div></CardContent></Card><Card className="rounded-2xl border-primary/5"><CardContent className="p-4 md:p-6 space-y-4"><h2 className="font-black">Payment Snapshot</h2><div><p className="text-xs text-muted-foreground">Successful payments</p><p className="text-2xl font-black">{o.successfulPayments||0}</p></div><div><p className="text-xs text-muted-foreground">Pending</p><p className="text-2xl font-black">{o.pendingPayments||0}</p></div><div><p className="text-xs text-muted-foreground">Rejected</p><p className="text-2xl font-black">{o.rejectedPayments||0}</p></div><div className="pt-2 border-t"><p className="text-xs text-muted-foreground">Points earned</p><p className="text-2xl font-black">{Number(o.pointsEarned||0).toLocaleString()}</p></div></CardContent></Card></div></>}
  </div>;
}
