"use client";

import { useEffect, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { CreditCard, Download, Search, ChevronLeft, ChevronRight, CheckCircle2, Clock3, XCircle, IndianRupee } from "lucide-react";
import { toast } from "sonner";

type Payment = { _id: string; userName: string; email: string; paymentStatus: string; paymentUtr?: string; paidAmount: number; joinedAt: string; pool?: { title: string; type: string; category: string } | null; payoutStatus: string };

export default function AdminPaymentsPage() {
  const [data, setData] = useState<Payment[]>([]); const [summary, setSummary] = useState<any>({});
  const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [range, setRange] = useState("30d"); const [page, setPage] = useState(1); const [pagination, setPagination] = useState<any>({ pages: 1, total: 0 });

  const load = async () => { setLoading(true); try { const params = new URLSearchParams({ search, status, page: String(page), limit: "25" }); if (range !== "all") { const d = new Date(); if (range === "today") d.setHours(0,0,0,0); else if (range === "7d") d.setDate(d.getDate()-7); else if (range === "30d") d.setDate(d.getDate()-30); else if (range === "90d") d.setDate(d.getDate()-90); params.set("from", d.toISOString().slice(0,10)); } const res = await fetch(`/api/admin/payments?${params}`); const json = await res.json(); if (!res.ok) throw new Error(json.error); setData(json.data || []); setSummary(json.summary || {}); setPagination(json.pagination || { pages: 1, total: 0 }); } catch (e: any) { toast.error(e.message || "Failed to load payments"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [status, range, page]);

  const exportCsv = async () => { const params = new URLSearchParams({ search, status, page: "1", limit: "100" }); const res = await fetch(`/api/admin/payments?${params}`); const json = await res.json(); const rows = (json.data || []).map((p: Payment) => [p.userName,p.email,p.pool?.title || "",p.paidAmount,p.paymentStatus,p.paymentUtr || "",new Date(p.joinedAt).toISOString(),p.payoutStatus]); const csv = [["User","Email","Pool","Amount","Payment Status","UTR","Date","Payout Status"],...rows].map(r=>r.map((v:any)=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"); const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); const a=document.createElement("a"); a.href=url; a.download="quizstreak-payments.csv"; a.click(); URL.revokeObjectURL(url); };

  const cards = [{label:"Verified Revenue",value:`₹${Number(summary.totalCollected||0).toLocaleString()}`,icon:IndianRupee},{label:"Successful",value:summary.successful||0,icon:CheckCircle2},{label:"Pending",value:summary.pending||0,icon:Clock3},{label:"Rejected",value:summary.rejected||0,icon:XCircle}];
  return <div className="p-4 md:p-6 space-y-6 max-w-7xl mx-auto">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-primary">Finance Console</p><h1 className="text-2xl md:text-3xl font-black tracking-tight">Payments</h1><p className="text-sm text-muted-foreground mt-1">Pool payment ledger, verification and payout tracking.</p></div><Button onClick={exportCsv} variant="outline" className="rounded-xl font-bold gap-2"><Download className="w-4 h-4"/>Export CSV</Button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{cards.map((c)=><Card key={c.label} className="rounded-2xl border-primary/5 shadow-sm"><CardContent className="p-4"><div className="flex justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground">{c.label}</p><p className="text-xl font-black mt-1">{c.value}</p></div><c.icon className="w-5 h-5 text-primary"/></div></CardContent></Card>)}</div>
    <Card className="rounded-2xl border-primary/5 shadow-sm"><CardContent className="p-3 md:p-4"><div className="flex flex-col lg:flex-row gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(setPage(1),load())} placeholder="Search user or UTR..." className="w-full h-10 rounded-xl border bg-background pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-primary/20"/></div><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-10 rounded-xl border px-3 text-sm font-bold bg-background"><option value="all">All statuses</option><option value="verified">Verified</option><option value="pending">Pending</option><option value="rejected">Rejected</option></select><select value={range} onChange={e=>{setRange(e.target.value);setPage(1)}} className="h-10 rounded-xl border px-3 text-sm font-bold bg-background"><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="all">All time</option></select><Button onClick={()=>{setPage(1);load()}} className="h-10 rounded-xl font-black">Apply</Button></div></CardContent></Card>
    <Card className="rounded-2xl border-primary/5 shadow-sm overflow-hidden"><div className="overflow-x-auto">{loading?<div className="p-5 space-y-3">{[1,2,3,4,5].map(i=><Skeleton key={i} className="h-12 w-full"/>)}</div>:<table className="w-full text-sm"><thead className="bg-muted/30 text-[9px] uppercase tracking-widest text-muted-foreground"><tr><th className="text-left p-4">User</th><th className="text-left p-4">Pool</th><th className="text-left p-4">Amount</th><th className="text-left p-4">Status</th><th className="text-left p-4">UTR</th><th className="text-left p-4">Joined</th><th className="text-left p-4">Payout</th></tr></thead><tbody>{data.map(p=><tr key={p._id} className="border-t border-primary/5 hover:bg-primary/[0.02]"><td className="p-4"><div className="font-bold">{p.userName}</div><div className="text-xs text-muted-foreground">{p.email}</div></td><td className="p-4"><div className="font-bold">{p.pool?.title || "Unknown pool"}</div><div className="text-xs text-muted-foreground">{p.pool?.category || ""}</div></td><td className="p-4 font-black">₹{Number(p.paidAmount||0).toLocaleString()}</td><td className="p-4"><span className={`px-2 py-1 rounded-full text-[10px] font-black uppercase ${p.paymentStatus==='verified'?'bg-emerald-500/10 text-emerald-700':p.paymentStatus==='pending'?'bg-amber-500/10 text-amber-700':'bg-red-500/10 text-red-700'}`}>{p.paymentStatus}</span></td><td className="p-4 font-mono text-xs">{p.paymentUtr || "—"}</td><td className="p-4 text-xs text-muted-foreground">{new Date(p.joinedAt).toLocaleString()}</td><td className="p-4 text-xs font-bold">{p.payoutStatus}</td></tr>)}{!data.length&&<tr><td colSpan={7} className="p-10 text-center text-muted-foreground">No payment records found.</td></tr>}</tbody></table>}</div><div className="p-3 border-t flex items-center justify-between text-xs"><span className="text-muted-foreground">{pagination.total||0} records</span><div className="flex items-center gap-2"><Button variant="outline" size="icon" disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft className="w-4 h-4"/></Button><span className="font-bold">{page} / {pagination.pages||1}</span><Button variant="outline" size="icon" disabled={page>=(pagination.pages||1)} onClick={()=>setPage(page+1)}><ChevronRight className="w-4 h-4"/></Button></div></div></Card>
  </div>;
}
